# Generated by Django 3.1.3 on 2021-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment_history',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='pacient',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Дата смерти (необязательно)', null=True, verbose_name='Died'),
        ),
    ]
