# Generated by Django 3.1.3 on 2021-01-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardfile', '0004_doctor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment_history',
            options={'ordering': ['start_date_of_treatment']},
        ),
        migrations.AlterField(
            model_name='treatment_history',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
